nodeLinker: node-modules

packageExtensions:
  '@nestjs/common@*':
    peerDependencies:
      'rxjs': '*'
      'reflect-metadata': '*'
    peerDependenciesMeta:
      'rxjs': { 'optional': true }
      'reflect-metadata': { 'optional': true }

  '@nestjs/core@*':
    peerDependencies:
      'rxjs': '*'
      'reflect-metadata': '*'
    peerDependenciesMeta:
      'rxjs': { 'optional': true }
      'reflect-metadata': { 'optional': true }
