import type { EndpointMeta } from './types';

/**
 * Example payloads for each admin API method.
 * Built from the swagger definitions + endpoint files.
 * Keep this file in sync with the gateway contracts.
 */
const ENDPOINT_PAYLOADS: Record<string, EndpointMeta> = {
  // ── Users ──────────────────────────────────────────────────────────────────
  signUp: {
    method: 'POST',
    path: '/users',
    description: 'Créer un nouvel utilisateur',
    examplePayload: { email: 'user@example.com', password: 'password123' },
    examplePathParams: null,
  },
  login: {
    method: 'POST',
    path: '/users/login',
    description: 'Authentifier un utilisateur',
    examplePayload: { email: 'user@example.com', password: 'password123' },
    examplePathParams: null,
  },
  refreshToken: {
    method: 'POST',
    path: '/users/refresh',
    description: "Rafraîchir le token d'accès",
    examplePayload: { refreshToken: 'your-refresh-token-here' },
    examplePathParams: null,
  },
  getMe: {
    method: 'GET',
    path: '/users/me',
    description: 'Récupérer le profil connecté',
    examplePayload: null,
    examplePathParams: null,
  },
  updateMe: {
    method: 'PATCH',
    path: '/users/me',
    description: 'Mettre à jour le profil connecté',
    examplePayload: {
      firstName: 'John',
      lastName: 'Doe',
      bio: 'Volunteer',
      avatarUrl: 'https://example.com/avatar.jpg',
    },
    examplePathParams: null,
  },
  deleteMe: {
    method: 'DELETE',
    path: '/users/me',
    description: 'Supprimer le compte connecté',
    examplePayload: null,
    examplePathParams: null,
  },
  listUsers: {
    method: 'GET',
    path: '/users',
    description: 'Lister tous les utilisateurs',
    examplePayload: null,
    examplePathParams: null,
  },
  getUser: {
    method: 'GET',
    path: '/users/:id',
    description: 'Récupérer un utilisateur par ID',
    examplePayload: null,
    examplePathParams: { id: 'user-uuid-here' },
  },
  updateUser: {
    method: 'PATCH',
    path: '/users/:id',
    description: 'Mettre à jour un utilisateur',
    examplePayload: { firstName: 'Jane', lastName: 'Smith', bio: 'Updated bio' },
    examplePathParams: { id: 'user-uuid-here' },
  },
  deleteUser: {
    method: 'DELETE',
    path: '/users/:id',
    description: 'Supprimer un utilisateur',
    examplePayload: null,
    examplePathParams: { id: 'user-uuid-here' },
  },
  listBadges: {
    method: 'GET',
    path: '/badges',
    description: 'Lister tous les badges',
    examplePayload: null,
    examplePathParams: null,
  },
  getBadge: {
    method: 'GET',
    path: '/badges/:id',
    description: 'Récupérer un badge par ID',
    examplePayload: null,
    examplePathParams: { id: 'badge-uuid-here' },
  },
  getBadgeBySlug: {
    method: 'GET',
    path: '/badges/slug/:slug',
    description: 'Récupérer un badge par slug',
    examplePayload: null,
    examplePathParams: { slug: 'badge-slug-here' },
  },
  createBadge: {
    method: 'POST',
    path: '/badges',
    description: 'Créer un badge',
    examplePayload: {
      name: 'Super Volunteer',
      slug: 'super-volunteer',
      description: 'Given to top volunteers',
      iconUrl: 'https://example.com/icon.png',
    },
    examplePathParams: null,
  },
  updateBadge: {
    method: 'PATCH',
    path: '/badges/:id',
    description: 'Mettre à jour un badge',
    examplePayload: { name: 'Updated Badge Name', description: 'Updated description' },
    examplePathParams: { id: 'badge-uuid-here' },
  },
  deleteBadge: {
    method: 'DELETE',
    path: '/badges/:id',
    description: 'Supprimer un badge',
    examplePayload: null,
    examplePathParams: { id: 'badge-uuid-here' },
  },
  addBadge: {
    method: 'POST',
    path: '/users/:id/badges',
    description: 'Attribuer un badge à un utilisateur',
    examplePayload: { badgeId: 'badge-uuid-here' },
    examplePathParams: { id: 'user-uuid-here' },
  },
  removeBadge: {
    method: 'DELETE',
    path: '/users/:id/badges/:badgeId',
    description: 'Retirer un badge à un utilisateur',
    examplePayload: null,
    examplePathParams: { id: 'user-uuid-here', badgeId: 'badge-uuid-here' },
  },
  incrementImpactScore: {
    method: 'POST',
    path: '/users/:id/impact-score',
    description: "Incrémenter le score d'impact",
    examplePayload: { points: 10 },
    examplePathParams: { id: 'user-uuid-here' },
  },
  getEventParticipants: {
    method: 'GET',
    path: '/users/event/:eventId/participants',
    description: "Participants d'un événement",
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here' },
  },
  getPostLikers: {
    method: 'GET',
    path: '/users/post/:postId/likers',
    description: "Likers d'un post",
    examplePayload: null,
    examplePathParams: { postId: 'post-uuid-here' },
  },

  // ── Events ─────────────────────────────────────────────────────────────────
  createEvent: {
    method: 'POST',
    path: '/events',
    description: 'Créer un événement',
    examplePayload: {
      title: 'Beach Cleanup Day',
      description: 'Join us for a beach cleanup!',
      localisationName: 'Plage du Prado, Marseille',
      startAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
      endAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3).toISOString(),
      maxParticipants: 50,
      tagIds: [],
    },
    examplePathParams: null,
  },
  updateEvent: {
    method: 'PATCH',
    path: '/events/:id',
    description: 'Mettre à jour un événement',
    examplePayload: { title: 'Updated Title', maxParticipants: 100 },
    examplePathParams: { id: 'event-uuid-here' },
  },
  deleteEvent: {
    method: 'DELETE',
    path: '/events/:id',
    description: 'Supprimer un événement',
    examplePayload: null,
    examplePathParams: { id: 'event-uuid-here' },
  },
  changeEventState: {
    method: 'PATCH',
    path: '/events/:id/state',
    description: "Changer l'état d'un événement",
    examplePayload: { state: 'PUBLISHED' },
    examplePathParams: { id: 'event-uuid-here' },
  },
  getEvent: {
    method: 'GET',
    path: '/events/:id',
    description: 'Récupérer un événement par ID',
    examplePayload: null,
    examplePathParams: { id: 'event-uuid-here' },
  },
  listEvents: {
    method: 'GET',
    path: '/events',
    description: 'Lister tous les événements',
    examplePayload: null,
    examplePathParams: null,
  },
  addRequirement: {
    method: 'POST',
    path: '/events/:id/requirements',
    description: 'Ajouter un prérequis à un événement',
    examplePayload: { label: 'Must be 18+', type: 'AGE' },
    examplePathParams: { id: 'event-uuid-here' },
  },
  removeRequirement: {
    method: 'DELETE',
    path: '/events/:id/requirements/:requirementId',
    description: 'Supprimer un prérequis',
    examplePayload: null,
    examplePathParams: { id: 'event-uuid-here', requirementId: 'req-uuid-here' },
  },
  listRequirements: {
    method: 'GET',
    path: '/events/:id/requirements',
    description: "Lister les prérequis d'un événement",
    examplePayload: null,
    examplePathParams: { id: 'event-uuid-here' },
  },
  createTag: {
    method: 'POST',
    path: '/tags',
    description: 'Créer un tag',
    examplePayload: { name: 'Ecology', color: '#22c55e' },
    examplePathParams: null,
  },
  updateTag: {
    method: 'PATCH',
    path: '/tags/:id',
    description: 'Mettre à jour un tag',
    examplePayload: { name: 'Environment', color: '#16a34a' },
    examplePathParams: { id: 'tag-uuid-here' },
  },
  deleteTag: {
    method: 'DELETE',
    path: '/tags/:id',
    description: 'Supprimer un tag',
    examplePayload: null,
    examplePathParams: { id: 'tag-uuid-here' },
  },
  listTags: {
    method: 'GET',
    path: '/tags',
    description: 'Lister tous les tags',
    examplePayload: null,
    examplePathParams: null,
  },
  getUserCreatedEventsSelf: {
    method: 'GET',
    path: '/events/created/me',
    description: 'Événements créés par moi',
    examplePayload: null,
    examplePathParams: null,
  },
  getUserParticipatedEventsSelf: {
    method: 'GET',
    path: '/events/participated/me',
    description: 'Événements auxquels je participe',
    examplePayload: null,
    examplePathParams: null,
  },
  getUserWishedEventsSelf: {
    method: 'GET',
    path: '/events/wished/me',
    description: 'Événements dans ma wishlist',
    examplePayload: null,
    examplePathParams: null,
  },

  // ── Social ─────────────────────────────────────────────────────────────────
  linkPostToEvent: {
    method: 'POST',
    path: '/social/events/:eventId/posts/:postId',
    description: 'Lier un post à un événement',
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here', postId: 'post-uuid-here' },
  },
  unlinkPostFromEvent: {
    method: 'DELETE',
    path: '/social/events/:eventId/posts/:postId',
    description: "Délier un post d'un événement",
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here', postId: 'post-uuid-here' },
  },
  getEventRelatedToPost: {
    method: 'GET',
    path: '/social/posts/:postId/related-event',
    description: 'Événement lié à un post',
    examplePayload: null,
    examplePathParams: { postId: 'post-uuid-here' },
  },
  getEventPosts: {
    method: 'GET',
    path: '/social/events/:eventId/related-posts',
    description: 'Posts liés à un événement',
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here' },
  },
  likePost: {
    method: 'POST',
    path: '/social/users/:userId/likes/:postId',
    description: 'Liker un post (admin)',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', postId: 'post-uuid-here' },
  },
  unlikePost: {
    method: 'DELETE',
    path: '/social/users/:userId/likes/:postId',
    description: 'Unliker un post (admin)',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', postId: 'post-uuid-here' },
  },
  likePostSelf: {
    method: 'POST',
    path: '/social/likes/:postId',
    description: 'Liker un post (self)',
    examplePayload: null,
    examplePathParams: { postId: 'post-uuid-here' },
  },
  unlikePostSelf: {
    method: 'DELETE',
    path: '/social/likes/:postId',
    description: 'Unliker un post (self)',
    examplePayload: null,
    examplePathParams: { postId: 'post-uuid-here' },
  },
  follow: {
    method: 'POST',
    path: '/social/users/:userId/follow/:followedId',
    description: 'Suivre un utilisateur (admin)',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', followedId: 'target-uuid-here' },
  },
  unfollow: {
    method: 'DELETE',
    path: '/social/users/:userId/follow/:followedId',
    description: 'Ne plus suivre (admin)',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', followedId: 'target-uuid-here' },
  },
  followSelf: {
    method: 'POST',
    path: '/social/follow/:followedId',
    description: 'Suivre un utilisateur (self)',
    examplePayload: null,
    examplePathParams: { followedId: 'target-uuid-here' },
  },
  unfollowSelf: {
    method: 'DELETE',
    path: '/social/follow/:followedId',
    description: 'Ne plus suivre (self)',
    examplePayload: null,
    examplePathParams: { followedId: 'target-uuid-here' },
  },
  block: {
    method: 'POST',
    path: '/social/users/:userId/block/:blockedId',
    description: 'Bloquer un utilisateur (admin)',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', blockedId: 'target-uuid-here' },
  },
  unblock: {
    method: 'DELETE',
    path: '/social/users/:userId/block/:blockedId',
    description: 'Débloquer (admin)',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', blockedId: 'target-uuid-here' },
  },
  blockSelf: {
    method: 'POST',
    path: '/social/block/:blockedId',
    description: 'Bloquer (self)',
    examplePayload: null,
    examplePathParams: { blockedId: 'target-uuid-here' },
  },
  unblockSelf: {
    method: 'DELETE',
    path: '/social/block/:blockedId',
    description: 'Débloquer (self)',
    examplePayload: null,
    examplePathParams: { blockedId: 'target-uuid-here' },
  },
  participate: {
    method: 'POST',
    path: '/social/users/:userId/events/:eventId/participate',
    description: 'Inscrire un user à un événement',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', eventId: 'event-uuid-here' },
  },
  unparticipate: {
    method: 'DELETE',
    path: '/social/users/:userId/events/:eventId/participate',
    description: "Désinscrire un user d'un événement",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', eventId: 'event-uuid-here' },
  },
  participateSelf: {
    method: 'POST',
    path: '/social/events/:eventId/participate',
    description: "M'inscrire à un événement",
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here' },
  },
  unparticipateSelf: {
    method: 'DELETE',
    path: '/social/events/:eventId/participate',
    description: "Me désinscrire d'un événement",
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here' },
  },
  wishEvent: {
    method: 'POST',
    path: '/social/users/:userId/events/:eventId/wish',
    description: 'Ajouter à la wishlist (admin)',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', eventId: 'event-uuid-here' },
  },
  unwishEvent: {
    method: 'DELETE',
    path: '/social/users/:userId/events/:eventId/wish',
    description: 'Retirer de la wishlist (admin)',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', eventId: 'event-uuid-here' },
  },
  wishEventSelf: {
    method: 'POST',
    path: '/social/events/:eventId/wish',
    description: 'Ajouter à ma wishlist',
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here' },
  },
  unwishEventSelf: {
    method: 'DELETE',
    path: '/social/events/:eventId/wish',
    description: 'Retirer de ma wishlist',
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here' },
  },
  createEventNode: {
    method: 'POST',
    path: '/social/events/:eventId',
    description: 'Créer nœud social événement',
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here' },
  },
  deleteEventNode: {
    method: 'DELETE',
    path: '/social/events/:eventId',
    description: 'Supprimer nœud social événement',
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here' },
  },
  ownEvent: {
    method: 'POST',
    path: '/social/users/:userId/events/:eventId/own',
    description: 'Assigner un événement à un user',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', eventId: 'event-uuid-here' },
  },
  disownEvent: {
    method: 'DELETE',
    path: '/social/users/:userId/events/:eventId/own',
    description: "Désassigner un événement d'un user",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', eventId: 'event-uuid-here' },
  },
  createPostNode: {
    method: 'POST',
    path: '/social/posts/:postId',
    description: 'Créer nœud social post',
    examplePayload: null,
    examplePathParams: { postId: 'post-uuid-here' },
  },
  deletePostNode: {
    method: 'DELETE',
    path: '/social/posts/:postId',
    description: 'Supprimer nœud social post',
    examplePayload: null,
    examplePathParams: { postId: 'post-uuid-here' },
  },
  ownPost: {
    method: 'POST',
    path: '/social/users/:userId/posts/:postId/own',
    description: 'Assigner un post à un user',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', postId: 'post-uuid-here' },
  },
  disownPost: {
    method: 'DELETE',
    path: '/social/users/:userId/posts/:postId/own',
    description: "Désassigner un post d'un user",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here', postId: 'post-uuid-here' },
  },
  createUserNode: {
    method: 'POST',
    path: '/social/users/:userId',
    description: 'Créer nœud social utilisateur',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  deleteUserNode: {
    method: 'DELETE',
    path: '/social/users/:userId',
    description: 'Supprimer nœud social utilisateur',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getUserLikes: {
    method: 'GET',
    path: '/social/users/:userId/likes',
    description: "Likes d'un utilisateur",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getUserLikesSelf: {
    method: 'GET',
    path: '/social/likes',
    description: 'Mes likes',
    examplePayload: null,
    examplePathParams: null,
  },
  getFeed: {
    method: 'GET',
    path: '/social/users/:userId/feed',
    description: "Feed d'un utilisateur",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getFeedSelf: {
    method: 'GET',
    path: '/social/feed/me',
    description: 'Mon feed',
    examplePayload: null,
    examplePathParams: null,
  },
  getUserPosts: {
    method: 'GET',
    path: '/social/users/:userId/posts',
    description: "Posts d'un utilisateur",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getUserPostsSelf: {
    method: 'GET',
    path: '/social/posts/me',
    description: 'Mes posts',
    examplePayload: null,
    examplePathParams: null,
  },
  getEventParticipantsSocial: {
    method: 'GET',
    path: '/social/events/:eventId/participants',
    description: 'Participants (social graph)',
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here' },
  },
  getPostLikersSocial: {
    method: 'GET',
    path: '/social/posts/:postId/likers',
    description: "Likers d'un post (social)",
    examplePayload: null,
    examplePathParams: { postId: 'post-uuid-here' },
  },
  getFollows: {
    method: 'GET',
    path: '/social/users/:userId/follows',
    description: "Abonnements d'un user",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getFollowers: {
    method: 'GET',
    path: '/social/users/:userId/followers',
    description: "Abonnés d'un user",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getFollowsSelf: {
    method: 'GET',
    path: '/social/follows',
    description: 'Mes abonnements',
    examplePayload: null,
    examplePathParams: null,
  },
  getFollowersSelf: {
    method: 'GET',
    path: '/social/followers',
    description: 'Mes abonnés',
    examplePayload: null,
    examplePathParams: null,
  },
  getBlocks: {
    method: 'GET',
    path: '/social/users/:userId/blocks',
    description: "Blocages d'un user",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getBlocksSelf: {
    method: 'GET',
    path: '/social/blocks',
    description: 'Mes blocages',
    examplePayload: null,
    examplePathParams: null,
  },
  getWhoBlockedMe: {
    method: 'GET',
    path: '/social/users/:userId/who-blocked-me',
    description: 'Qui a bloqué cet user',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getWhoBlockedMeSelf: {
    method: 'GET',
    path: '/social/who-blocked-me',
    description: "Qui m'a bloqué",
    examplePayload: null,
    examplePathParams: null,
  },
  getEventNode: {
    method: 'GET',
    path: '/social/events/:eventId',
    description: "Nœud social d'un événement",
    examplePayload: null,
    examplePathParams: { eventId: 'event-uuid-here' },
  },
  getPostNode: {
    method: 'GET',
    path: '/social/posts/:postId',
    description: "Nœud social d'un post",
    examplePayload: null,
    examplePathParams: { postId: 'post-uuid-here' },
  },
  getUserNode: {
    method: 'GET',
    path: '/social/users/:userId',
    description: "Nœud social d'un user",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getUserCreatedEvents: {
    method: 'GET',
    path: '/social/users/:userId/events/created',
    description: 'Événements créés par un user',
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getUserParticipatedEvents: {
    method: 'GET',
    path: '/social/users/:userId/events/participated',
    description: "Participations d'un user",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getUserWishedEvents: {
    method: 'GET',
    path: '/social/users/:userId/events/wished',
    description: "Wishlist d'un user",
    examplePayload: null,
    examplePathParams: { userId: 'user-uuid-here' },
  },
  getUserCreatedEventsSelfSocial: {
    method: 'GET',
    path: '/social/events/created',
    description: 'Mes événements créés (social)',
    examplePayload: null,
    examplePathParams: null,
  },
  getUserParticipatedEventsSelfSocial: {
    method: 'GET',
    path: '/social/events/participated',
    description: 'Mes participations (social)',
    examplePayload: null,
    examplePathParams: null,
  },
  getUserWishedEventsSelfSocial: {
    method: 'GET',
    path: '/social/events/wished',
    description: 'Ma wishlist (social)',
    examplePayload: null,
    examplePathParams: null,
  },

  // ── Health ─────────────────────────────────────────────────────────────────
  healthCheck: {
    method: 'GET',
    path: '/health',
    description: 'Health check du service',
    examplePayload: null,
    examplePathParams: null,
  },
};

export function getEndpointMeta(methodName: string): EndpointMeta | null {
  return ENDPOINT_PAYLOADS[methodName] ?? null;
}
