import type { BadgeDefinition, BadgeVariant } from './badge.types';

export const BADGE_VARIANTS: BadgeVariant[] = [
  'EVENT_PARTICIPATION_TIER_1',
  'EVENT_PARTICIPATION_TIER_2',
  'EVENT_PARTICIPATION_TIER_3',
  'EVENT_PARTICIPATION_TIER_4',
  'EVENT_SOCIAL_TIER_1',
  'EVENT_SOCIAL_TIER_2',
  'EVENT_ECOLOGY_TIER_1',
  'EVENT_ECOLOGY_TIER_2',
  'EVENT_HYBRID_ECO_SOCIAL_TIER_1',
  'SOCIAL_LIKE_COUNT_10',
  'EVENT_WISHLIST_COUNT_10',
  'COMMUNITY_POST_COUNT_1',
  'EVENT_HOST_COUNT_1',
];

export const BADGE_REGISTRY: Record<BadgeVariant, BadgeDefinition> = {
  EVENT_PARTICIPATION_TIER_1: {
    variant: 'EVENT_PARTICIPATION_TIER_1',
    name: 'Premier Pas',
    description: 'Participer à 1 événement',
    category: 'participation',
    categoryLabel: 'Badge de participation',
    designDescription: 'Couleur Bronze, médaille de bronze',
    icon: 'medal',
    iconLibrary: 'FontAwesome5',
  },
  EVENT_PARTICIPATION_TIER_2: {
    variant: 'EVENT_PARTICIPATION_TIER_2',
    name: 'Engagé·e',
    description: 'Participer à 5 événements',
    category: 'participation',
    categoryLabel: 'Badge de participation',
    designDescription: "Couleur Argent, médaille d'argent",
    icon: 'medal',
    iconLibrary: 'FontAwesome5',
  },
  EVENT_PARTICIPATION_TIER_3: {
    variant: 'EVENT_PARTICIPATION_TIER_3',
    name: 'Pilier',
    description: 'Participer à 10 événements',
    category: 'participation',
    categoryLabel: 'Badge de participation',
    designDescription: "Couleur Or, médaille d'or",
    icon: 'medal',
    iconLibrary: 'FontAwesome5',
  },
  EVENT_PARTICIPATION_TIER_4: {
    variant: 'EVENT_PARTICIPATION_TIER_4',
    name: 'Figure locale',
    description: 'Participer à 20 événements',
    category: 'participation',
    categoryLabel: 'Badge de participation',
    designDescription: 'Couleur "diamant", couronne',
    icon: 'crown',
    iconLibrary: 'FontAwesome5',
    isDiamond: true,
  },
  EVENT_SOCIAL_TIER_1: {
    variant: 'EVENT_SOCIAL_TIER_1',
    name: 'Cœur Solidaire',
    description: 'Participer à 1 événement socio',
    category: 'participation',
    categoryLabel: 'Badge de participation',
    designDescription: 'Couleur socio avec un "1"',
    tierText: '1',
  },
  EVENT_SOCIAL_TIER_2: {
    variant: 'EVENT_SOCIAL_TIER_2',
    name: 'Tisseur·se de liens',
    description: 'Participer à 5 événements socio',
    category: 'participation',
    categoryLabel: 'Badge de participation',
    designDescription: 'Couleur socio avec un "5"',
    tierText: '5',
  },
  EVENT_ECOLOGY_TIER_1: {
    variant: 'EVENT_ECOLOGY_TIER_1',
    name: "Graine d'écolo",
    description: 'Participer à 1 événement éco',
    category: 'participation',
    categoryLabel: 'Badge de participation',
    designDescription: 'Couleur éco avec un "1"',
    tierText: '1',
  },
  EVENT_ECOLOGY_TIER_2: {
    variant: 'EVENT_ECOLOGY_TIER_2',
    name: 'Main Verte',
    description: 'Participer à 5 événements éco',
    category: 'participation',
    categoryLabel: 'Badge de participation',
    designDescription: 'Couleur éco avec un "5"',
    tierText: '5',
  },
  EVENT_HYBRID_ECO_SOCIAL_TIER_1: {
    variant: 'EVENT_HYBRID_ECO_SOCIAL_TIER_1',
    name: 'Éco-Solidaire',
    description: 'Participer à 5 événements éco et 5 événements socio',
    category: 'participation',
    categoryLabel: 'Badge de participation',
    designDescription: 'Couleur éco, bordure socio, avec deux "5"',
    tierText: '5 / 5',
    isHybrid: true,
  },
  SOCIAL_LIKE_COUNT_10: {
    variant: 'SOCIAL_LIKE_COUNT_10',
    name: 'Soutien du cœur',
    description: 'Liker 10 posts',
    category: 'interaction',
    categoryLabel: "Badge d'interaction",
    designDescription: 'Couleur rouge, avec un cœur',
    icon: 'heart',
    iconLibrary: 'FontAwesome5',
    badgeNumber: 10,
  },
  EVENT_WISHLIST_COUNT_10: {
    variant: 'EVENT_WISHLIST_COUNT_10',
    name: 'Curieux·se',
    description: 'Wishlist 10 événements',
    category: 'interaction',
    categoryLabel: "Badge d'interaction",
    designDescription: 'Couleur verte, avec un cœur',
    icon: 'heart',
    iconLibrary: 'FontAwesome5',
    badgeNumber: 10,
  },
  COMMUNITY_POST_COUNT_1: {
    variant: 'COMMUNITY_POST_COUNT_1',
    name: 'Première Plume',
    description: 'Poster 1 post',
    category: 'interaction',
    categoryLabel: "Badge d'interaction",
    designDescription: 'Couleur neutre, avec une "bulle"',
    icon: 'comment-alt',
    iconLibrary: 'FontAwesome5',
  },
  EVENT_HOST_COUNT_1: {
    variant: 'EVENT_HOST_COUNT_1',
    name: 'Bâtisseur·se',
    description: 'Poster 1 événement',
    category: 'interaction',
    categoryLabel: "Badge d'interaction",
    designDescription: 'Couleur dorée, avec un calendrier',
    icon: 'calendar-alt',
    iconLibrary: 'FontAwesome5',
  },
};
