import { UserRoles } from '@volontariapp/shared';
import type { EndpointDefinition } from '../types';
import type {
  ActionSuccessWebResponse,
  GetEventPostsWebRequest,
  GetUserLikesWebRequest,
  GetEventParticipantsWebRequest,
  GetUserPostsWebRequest,
  GetFeedWebRequest,
  GetMyFollowsWebRequest,
  GetMyFollowersWebRequest,
  GetMyBlocksWebRequest,
  GetWhoBlockedMeWebRequest,
  ListUsersWebResponse,
  EventIdWebResponse,
  IdsListWebResponse,
  ExistsWebResponse,
  GetUserEventsRequest,
  GetUserWishesRequest,
  GetUserParticipationsRequest,
} from '@volontariapp/contracts';

export const SOCIAL_ENDPOINTS = {
  LINK_POST_TO_EVENT: {
    path: '/social/events/:eventId/posts/:postId',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  UNLINK_POST_FROM_EVENT: {
    path: '/social/events/:eventId/posts/:postId',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  GET_EVENT_RELATED_TO_POST: {
    path: '/social/posts/:postId/related-event',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, EventIdWebResponse>,
  GET_EVENT_POSTS: {
    path: '/social/events/:eventId/related-posts',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetEventPostsWebRequest, IdsListWebResponse>,
  LIKE_POST: {
    path: '/social/users/:userId/likes/:postId',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  UNLIKE_POST: {
    path: '/social/users/:userId/likes/:postId',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  LIKE_POST_SELF: {
    path: '/social/likes/:postId',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  UNLIKE_POST_SELF: {
    path: '/social/likes/:postId',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  CREATE_EVENT_NODE: {
    path: '/social/events/:eventId',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  DELETE_EVENT_NODE: {
    path: '/social/events/:eventId',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  OWN_EVENT: {
    path: '/social/users/:userId/events/:eventId/own',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  DISOWN_EVENT: {
    path: '/social/users/:userId/events/:eventId/own',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  PARTICIPATE: {
    path: '/social/users/:userId/events/:eventId/participate',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  UNPARTICIPATE: {
    path: '/social/users/:userId/events/:eventId/participate',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  WISH_EVENT: {
    path: '/social/users/:userId/events/:eventId/wish',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  UNWISH_EVENT: {
    path: '/social/users/:userId/events/:eventId/wish',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  PARTICIPATE_SELF: {
    path: '/social/events/:eventId/participate',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  UNPARTICIPATE_SELF: {
    path: '/social/events/:eventId/participate',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  WISH_EVENT_SELF: {
    path: '/social/events/:eventId/wish',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  UNWISH_EVENT_SELF: {
    path: '/social/events/:eventId/wish',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  CREATE_POST_NODE: {
    path: '/social/posts/:postId',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  DELETE_POST_NODE: {
    path: '/social/posts/:postId',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  OWN_POST: {
    path: '/social/users/:userId/posts/:postId/own',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  DISOWN_POST: {
    path: '/social/users/:userId/posts/:postId/own',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  FOLLOW: {
    path: '/social/users/:userId/follow/:followedId',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  UNFOLLOW: {
    path: '/social/users/:userId/follow/:followedId',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  BLOCK: {
    path: '/social/users/:userId/block/:blockedId',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  UNBLOCK: {
    path: '/social/users/:userId/block/:blockedId',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  FOLLOW_SELF: {
    path: '/social/follow/:followedId',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  UNFOLLOW_SELF: {
    path: '/social/follow/:followedId',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  BLOCK_SELF: {
    path: '/social/block/:blockedId',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  UNBLOCK_SELF: {
    path: '/social/block/:blockedId',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  CREATE_USER_NODE: {
    path: '/social/users/:userId',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  DELETE_USER_NODE: {
    path: '/social/users/:userId',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  GET_USER_LIKES: {
    path: '/social/users/:userId/likes',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<GetUserLikesWebRequest, IdsListWebResponse>,
  GET_USER_LIKES_SELF: {
    path: '/social/likes',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetUserLikesWebRequest, IdsListWebResponse>,
  GET_POST_LIKERS: {
    path: '/social/posts/:postId/likers',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetUserLikesWebRequest, IdsListWebResponse>,
  GET_USER_CREATED_EVENTS: {
    path: '/social/users/:userId/events/created',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<GetUserEventsRequest, IdsListWebResponse>,
  GET_USER_PARTICIPATED_EVENTS: {
    path: '/social/users/:userId/events/participated',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<GetUserParticipationsRequest, IdsListWebResponse>,
  GET_USER_WISHED_EVENTS: {
    path: '/social/users/:userId/events/wished',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<GetUserWishesRequest, IdsListWebResponse>,
  GET_USER_CREATED_EVENTS_SELF: {
    path: '/social/events/created',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetUserEventsRequest, IdsListWebResponse>,
  GET_USER_PARTICIPATED_EVENTS_SELF: {
    path: '/social/events/participated',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetUserParticipationsRequest, IdsListWebResponse>,
  GET_USER_WISHED_EVENTS_SELF: {
    path: '/social/events/wished',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetUserWishesRequest, IdsListWebResponse>,
  GET_EVENT_NODE: {
    path: '/social/events/:eventId',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ExistsWebResponse>,
  GET_EVENT_PARTICIPANTS: {
    path: '/social/events/:eventId/participants',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetEventParticipantsWebRequest, IdsListWebResponse>,
  GET_USER_POSTS: {
    path: '/social/users/:userId/posts',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<GetUserPostsWebRequest, IdsListWebResponse>,
  GET_FEED: {
    path: '/social/users/:userId/feed',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<GetFeedWebRequest, IdsListWebResponse>,
  GET_USER_POSTS_SELF: {
    path: '/social/posts/me',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetUserPostsWebRequest, IdsListWebResponse>,
  GET_FEED_SELF: {
    path: '/social/feed/me',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetFeedWebRequest, IdsListWebResponse>,
  GET_POST_NODE: {
    path: '/social/posts/:postId',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ExistsWebResponse>,
  GET_FOLLOWS: {
    path: '/social/users/:userId/follows',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<GetMyFollowsWebRequest, IdsListWebResponse>,
  GET_FOLLOWERS: {
    path: '/social/users/:userId/followers',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<GetMyFollowersWebRequest, IdsListWebResponse>,
  GET_BLOCKS: {
    path: '/social/users/:userId/blocks',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<GetMyBlocksWebRequest, IdsListWebResponse>,
  GET_WHO_BLOCKED_ME: {
    path: '/social/users/:userId/who-blocked-me',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<GetWhoBlockedMeWebRequest, IdsListWebResponse>,
  GET_FOLLOWS_SELF: {
    path: '/social/follows',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetMyFollowsWebRequest, ListUsersWebResponse>,
  GET_FOLLOWERS_SELF: {
    path: '/social/followers',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetMyFollowersWebRequest, ListUsersWebResponse>,
  GET_BLOCKS_SELF: {
    path: '/social/blocks',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetMyBlocksWebRequest, IdsListWebResponse>,
  GET_WHO_BLOCKED_ME_SELF: {
    path: '/social/who-blocked-me',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetWhoBlockedMeWebRequest, IdsListWebResponse>,
  GET_USER_NODE: {
    path: '/social/users/:userId',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, ExistsWebResponse>,
} as const;
