import { UserRoles } from '@volontariapp/shared';
import type { EndpointDefinition } from '../types';
import type {
  SignUpRequest,
  SignUpWebResponse,
  LoginRequest,
  LoginWebResponse,
  RefreshTokenRequest,
  CreateBadgeRequest,
  BadgeWebResponse,
  UpdateBadgeRequest,
  UpdateUserRequest,
  UserWebResponse,
  AddBadgeToUserRequest,
  IncrementImpactScoreRequest,
  ActionSuccessWebResponse,
  ListBadgesRequest,
  ListBadgesWebResponse,
  ListUsersRequest,
  ListUsersWebResponse,
  GetEventParticipantsWebRequest,
  GetPostLikersWebRequest,
} from '@volontariapp/contracts';

export const USER_ENDPOINTS = {
  SIGN_UP: {
    path: '/users',
    method: 'POST',
    requiresAuth: false,
  } as EndpointDefinition<SignUpRequest, SignUpWebResponse>,
  LOGIN: {
    path: '/users/login',
    method: 'POST',
    requiresAuth: false,
  } as EndpointDefinition<LoginRequest, LoginWebResponse>,
  REFRESH_TOKEN: {
    path: '/users/refresh',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<RefreshTokenRequest, LoginWebResponse>,
  CREATE_BADGE: {
    path: '/badges',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<CreateBadgeRequest, BadgeWebResponse>,
  UPDATE_BADGE: {
    path: '/badges/:id',
    method: 'PATCH',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<UpdateBadgeRequest, BadgeWebResponse>,
  DELETE_BADGE: {
    path: '/badges/:id',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, void>,
  UPDATE_USER: {
    path: '/users/:id',
    method: 'PATCH',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<UpdateUserRequest, UserWebResponse>,
  DELETE_USER: {
    path: '/users/:id',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, void>,
  ADD_BADGE: {
    path: '/users/:id/badges',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<AddBadgeToUserRequest, void>,
  REMOVE_BADGE: {
    path: '/users/:id/badges/:badgeId',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, void>,
  INCREMENT_IMPACT_SCORE: {
    path: '/users/:id/impact-score',
    method: 'POST',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<IncrementImpactScoreRequest, void>,
  UPDATE_ME: {
    path: '/users/me',
    method: 'PATCH',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<UpdateUserRequest, UserWebResponse>,
  DELETE_ME: {
    path: '/users/me',
    method: 'DELETE',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, ActionSuccessWebResponse>,
  LIST_BADGES: {
    path: '/badges',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<ListBadgesRequest, ListBadgesWebResponse>,
  GET_BADGE_BY_SLUG: {
    path: '/badges/slug/:slug',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, BadgeWebResponse>,
  GET_BADGE: {
    path: '/badges/:id',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, BadgeWebResponse>,
  LIST_USERS: {
    path: '/users',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<ListUsersRequest, ListUsersWebResponse>,
  GET_USER: {
    path: '/users/:id',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ADMIN],
  } as EndpointDefinition<void, UserWebResponse>,
  GET_PUBLIC_USER: {
    path: '/users/:id/public',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, UserWebResponse>,
  GET_ME: {
    path: '/users/me',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<void, UserWebResponse>,
  GET_EVENT_PARTICIPANTS: {
    path: '/users/event/:eventId/participants',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetEventParticipantsWebRequest, ListUsersWebResponse>,
  GET_POST_LIKERS: {
    path: '/users/post/:postId/likers',
    method: 'GET',
    requiresAuth: true,
    roles: [UserRoles.ORGANIZATION, UserRoles.VOLUNTEER, UserRoles.ADMIN],
  } as EndpointDefinition<GetPostLikersWebRequest, ListUsersWebResponse>,
} as const;
