name: CI Mobile (Expo)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-pipeline:
    uses: Volontariapp/ci-tools/.github/workflows/nativapp-ci.yml@main
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
